on: [push]

name: Run tests

jobs:
    tests:
        name: tests
        runs-on: ubuntu-latest
        continue-on-error: true
        env:
            RUSTFLAGS: -D warnings
            CARGO_TERM_COLOR: always
        steps:
            - uses: actions/checkout@v3
            - name: Setup Rust
              uses: ./.github/actions/setup-rust

            - name: Install latest nextest release
              uses: taiki-e/install-action@nextest

            - name: Run tests
              run: cargo nextest run --all-targets
